config/routes.rb
Rails.application.routes.draw do

  resources :expense_reports do
    collection do
      get 'search'
    end
    resources :comments
  end

  # resources :expense_report, only: %i[new create show]
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }

  # get 'pages/users'
  get 'pages/admin'
  resources :expenses do
    collection do
      get 'search'
    end
    resources :comments 
    member do
      patch 'approve'
      patch 'reject'
    end
  end
  resources :pages do
    member do
      patch 'terminate'
      patch 'activate'
    end
  end

  root to: 'pages#home'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :expense_report, optional: true
  belongs_to :expense, optional: true
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :set_expense, only: %i[new index create destroy]
  before_action :authenticate_user!, except: [:show , :index]

  # GET /comments or /comments.json
  def index
    @comments = @expense.comments
    @comment = Comment.new
    set_commentable_type
  end

  # GET /comments/1 or /comments/1.json
  def show
    @expense = @comment.expense
  end

  # # GET /comments/new
  def new
    @comment = Comment.new
    set_commentable_type
  end

  # GET /comments/1/edit
  def edit
    @expense = @comment.expense
  end

  # POST /comments or /comments.json
  def create

    @comment = Comment.new(comment_params)
    
    @comment.user = current_user

    set_commentable_type
    if @comment.commentable_type == "Expense"
      respond_to do |format|
        if @comment.save
          format.html { redirect_to expense_comments_url(@comment), notice: "Comment was successfully created." }
          format.json { render :show, status: :created, location: @comment }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    elsif @comment.commentable_type == "Expense Report"
      respond_to do |format|
        if @comment.save
          format.html { redirect_to expense_report_comments_url(@comment), notice: "Comment was successfully created." }
          format.json { render :show, status: :created, location: @comment }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @comment.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to expense_comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to expense_comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_expense
      begin
        @expense = Expense.find(params[:expense_id])  
      rescue => exception
        @expense = ExpenseReport.find(params[:expense_report_id])
      end
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content)
    end

    def set_commentable_type
      begin
        @comment.expense = @expense
        @comment.commentable_type = "Expense"
      rescue => exception
        @comment.expense_report = @expense
        @comment.commentable_type = "Expense Report"
      end
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>">
  <p>
    <strong>Content:</strong>
    <%= comment.content %>
  </p>

  <p>
    <strong>Commentable type:</strong>
    <%= comment.commentable_type %>
  </p>

<!--
  <p>
    <strong>Expense:</strong>
    <%= comment.expense_id %>
  </p>
-->
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [@expense,comment]) do |form| %>
  <% if form.object.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(form.object.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% form.object.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

<!--
  <div>
    <%= form.label :commentable_type, style: "display: block" %>
    <%= form.text_field :commentable_type %>
  </div>
-->

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_new.html.erb
<%= form_with(model: [@expense,@comment]) do |form| %>
  <% if form.object.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(form.object.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% form.object.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.text_area :content %>
  </div>

  <div>
    <%= form.label :commentable_type, style: "display: block" %>
    <%= form.text_field :commentable_type %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", expense_comment_path(@expense, @comment) %> |
  <%= link_to "Back to comments", expense_comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", expense_comment_path(@expense, comment) %>
    </p>
  <% end %>
</div>
<% if @comment.expense_id.present? %>
<%= link_to "New comment", new_expense_comment_path(@expense)%>
<%= link_to "Back to expenses", expenses_path %>
<% elsif @comment.expense_report_id.present?%>
<%= link_to "New comment", new_expense_report_comment_path(@expense)%>
<%= link_to "Back to expense reports", expense_reports_path %>
<% end %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
<% if @comment.commentable_type == "Expense" %>
  <%= link_to "Back to comments", expense_comments_path(@expense) %>
  <% else @comment.commentable_type == "Expense Report" %>
  <%= link_to "Back to comments", expense_report_comments_path(@expense) %>
  <%end%>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

  <%= render @comment %>

<div>
<% if @comment.commentable_type == "Expense" %>
  <%= link_to "Edit this comment", edit_expense_comment_path(@expense, @comment) %> |
  <%= link_to "Back to comments", expense_comments_path(@expense) %>
  <%= button_to "Destroy this comment", expense_comment_path(@expense, @comment), method: :delete %>
<% elsif @comment.commentable_type == "Expense Report" %>
  <%= link_to "Edit this comment", edit_expense_report_comment_path(@expense, @comment) %> |
  <%= link_to "Back to comments", expense_report_comments_path(@expense) %>
  <%= button_to "Destroy this comment", expense_report_comment_path(@expense, @comment), method: :delete %>
<%end%>
</div>