config/routes.rb
Rails.application.routes.draw do

  resources :expense_reports do
    collection do
      get 'search'
    end
    resources :comments
  end

  # resources :expense_report, only: %i[new create show]
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations'
  }

  # get 'pages/users'
  get 'pages/admin'
  resources :expenses do
    collection do
      get 'search'
    end
    resources :comments 
    member do
      patch 'approve'
      patch 'reject'
    end
  end
  resources :pages do
    member do
      patch 'terminate'
      patch 'activate'
    end
  end

  root to: 'pages#home'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %i[ show edit update destroy approve reject]
  # before_action :check_approval_status, only: %i[approve reject]
  before_action :authenticate_user!, except: [:show , :index]
  before_action :check_employement_status, except: %i[search index show]

  def search
    search_term = params[:search_term].strip.downcase

    if search_term.present?
      # Perform the search using the provided search_term
      @expenses = @user.get_expenses.joins(:user).where("lower(users.name) LIKE ?", "%#{search_term}%")
    else
      # If no search term is provided, display all expenses
      @expenses = @user.get_expenses
    end

    render :index
  end
  
  # GET /expenses or /expenses.json
  def index
    if params[:user_id].present?
      @user = User.find(params[:user_id])
      @expenses = @user.get_expenses
    else
      @expenses = @user.get_expenses
    end
  end
  
  def approve
    # Send approval email
    UserMailer.approval_email(@expense).deliver_now
    if @expense.approval_status == "pending"
      @expense.update(approval_status: 'Approved')
      redirect_to expenses_path, notice: 'Expense approved successfully.'
    else
      redirect_to expenses_path, notice: 'Expense is already ' + @expense.approval_status + '.'
    end

  end
  def reject
    # Send rejection email
    UserMailer.rejection_email(@expense).deliver_now
    if @expense.approval_status == "pending"
      @expense.update(approval_status: 'Rejected')
      redirect_to expenses_path, notice: 'Expense rejected successfully.'
    else
      redirect_to expenses_path, notice: 'Expense is already ' + @expense.approval_status + '.'
    end
  end

  # GET /expenses/1 or /expenses/1.json
  def show
    # @expense = Expense.find(params[:id])
    @comments = @expense.comments
    @comment = Comment.new
    @users = User.all
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses or /expenses.json
  def create
    @expense = Expense.new(expense_params)
    @expense.user = current_user
    respond_to do |format|
      if @expense.save
        # format.html { redirect_to expense_url(@expense), notice: "Expense was successfully created." }
        # format.json { render :show, status: :created, location: @expense }
        validation_result = validate_invoice(@expense.invoice_number)
      
        if validation_result
        # Validation successful, expense needs manual approval
          @expense.update(invoice_validated: validation_result)
          format.html {redirect_to expense_url(@expense), notice: "Expense was successfully created. Pending manual approval."}
        else
        # Validation failed, automatically reject the expense
          format.html {redirect_to new_expense_url(@expense), alert: "Expense validation failed. Expense rejected."}
          @expense.destroy
        end

      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to expense_url(@expense), notice: "Expense was successfully updated." }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense.destroy

    respond_to do |format|
      format.html { redirect_to expenses_url, notice: "Expense was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # def check_approval_status(@t)
    #   if @t.approval_status == "pending"
    #     return 
    #   end
    # end

    # def set_expenses
    #   if @user.admin
    #     @expenses = Expense.all
    #   else
    #     @expenses = @user.expenses
    #   end
    # end

    # Only allow a list of trusted parameters through.
    def expense_params
      params.require(:expense).permit(:date, :description, :amount, :invoice_number, :invoice_validated,:invoice)
    end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/expenses/_expense.html.erb
<div id="<%= dom_id(expense) %>">
  <p>
    <strong>Date:</strong>
    <%= expense.date %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= expense.description %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= expense.amount %>
  </p>

  <p>
    <strong>Invoice number:</strong>
    <%= expense.invoice_number %>
  </p>

  <p>
    <strong>Invoice validated:</strong>
    <%= expense.invoice_validated %>
  </p>

  <p>
    <strong>User:</strong>
     <%= expense.user.name %>
  </p>
  <p>
    <strong>Approval Status:</strong>
     <%= expense.approval_status %>
  </p>
  <p>
  <% if expense.invoice.attached?%>
  <%= link_to expense.invoice.filename, expense.invoice%>
  <% end %>
  </p>

  
  <% if @user.admin %>
    <div class="button-container">
      <%= form_with(url: approve_expense_path(expense), method: :patch) do |form| %>
        <%= form.submit 'Approve',class: 'approve-button' %>
      <% end %>

      <%= form_with(url: reject_expense_path(expense), method: :patch) do |form| %>
        <%= form.submit 'Reject',class: 'reject-button' %>
      <% end %>
    </div>
  <% end %>

  <% if @comments.present? %>
    <h2>Comments:</h2>
    <% @comments.each do |comment| %>
      <p><strong><%= comment.user.name %></strong>: <%= comment.content %></p>
    <% end %>
  <% else %>
    <p>No comments yet.</p>
  <% end %>

</div>

app/views/expenses/_form.html.erb
<%= form_with(model: expense, html: { class: "expense-form" }) do |form| %>
  <% if expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.label :invoice_number, style: "display: block" %>
    <%= form.number_field :invoice_number %>
  </div>

<!--The following snippet is for enabling user to attach a file-->
  <div>
    <%= form.label :invoice %>
    <%= form.file_field :invoice %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing expense</h1>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Show this expense", @expense %> |
  <%= link_to "Back to expenses", expenses_path %>
</div>

app/views/expenses/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Expense Tracker</title>
  <link rel="stylesheet" href="styles.css"> <!-- Link to the styles.css file -->
</head>
<body>
  <nav class="navbar-index"> <!-- Use the new navbar class specific to the index page -->
    <h1>Expenses</h1>
      <%= form_tag(search_expenses_path, method: :get) do %>
        <%= text_field_tag :search_term, params[:search_term], placeholder: "Search by user name" %>
        <%= submit_tag "Search" %>
      <% end %>
    <div>
      <%= link_to "New expense", new_expense_path %>
      <%= link_to "Expense Reports", expense_reports_path %>
      <%= link_to "Back to Home", root_path %>
    </div>
  </nav>

  <div id="expenses">
    <% @expenses.each do |expense| %>
      <% @comments = expense.comments %>
      <%= render expense %>
      <%= link_to "Show this expense", expense_path(expense)%>
      <%= button_to "Destroy this expense", expense, method: :delete %>
    <% end %>
  </div>
</body>
</html>

app/views/expenses/new.html.erb
<%# <h1>New expense</h1> %>
  <link rel="stylesheet" href="styles.css"> <!-- Link to the styles.css file -->

<div class="navbar"> <!-- Use the new CSS class for the navbar -->
    <a href="#">New Expense</a>
  </div>

<%= render "form", expense: @expense %>

<br>

<div>
  <%= link_to "Back to expenses", expenses_path %>
</div>

app/views/expenses/show.html.erb
<%= render @expense %>

<div>
  <%= link_to "Edit this expense", edit_expense_path(@expense) %> |
  <%= link_to "Back to expenses", expenses_path %> |
  <%= link_to "Comments", expense_comments_path(@expense)%>

  <%= button_to "Destroy this expense", @expense, method: :delete %>
</div>